version: "3"
volumes:          #define volume for docker
  disk-mysql:
  disk-it:
services:
  mysql:
    image: mysql:5
    container_name: snipe_mysql
    restart: always
    volumes:
      - disk-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=CBC@3521
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=CBC@3521
      - MYSQL_DATABASE=snipeit
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - mysql
    volumes:
      - disk-it:/config
    environment:
      - APP_URL= your application URL IE 192.168.3.30:8080
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=CBC@3521
      - PGID=1000
      - PUID=1000
    ports:
      - "80:80"
